### ISSUE TITLE
how to use this with Angular2

### ISSUE THREAD

**Issue by geyang** [tjvantoll/nativescript-template-drawer#1]
Hi Tj,

Thanks for this great template! I'm using nativescript with Angular2. What does it take to adapt the drawer module to use with Angular2?

Thanks!
Ge

**Comment by tjvantoll** [comment]
Hi @episodeyang,

Sorry I missed this comment. Unfortunately right now you can’t use this drawer control in an ng2 NativeScript app. We’re working on it though, and [this](https://github.com/NativeScript/nativescript-angular/issues/100) is the issue to follow for updates on that.

I’m going to close this issue because, once we do support using the RadSideDrawer in ng2 apps, we’ll have to build a new template for using drawers.
